### ISSUE TITLE
Manual modifications to run models with OpenM++ v1.15.4

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#10]
Received via email

> OpenM developers (i.e., Steve and Anatoly) tend to use the most recent version of Visual Studio available. Right now, I think that is 2022 Visual Studio. Internal at StatCan, we only have access to 2019 Visual Studio. What we have noticed is that, when we bring in the latest releases of OpenM, we need to make several manual changes to our systems and code for our models (and 2019 Visual Studio) to function. We’ve described this issue to OpenM Inc, and they feel that it is related to versions of Visual Studio.
> 
> If there is willingness from your team, it would be nice to have changes made to the newest releases of OpenM to make them backwards compatible with Visual Studio so that our many manual work arounds aren’t needed.
> 
> If you’d like more information, please let us know.
> 
> Thanks so much,
> 
> Rochelle

We would require to list all manual changes made to their system and code for their models to run. A screen share session with Rochelle and Deirdre would most likely work best in this case.

Note that these changes may not be necessary in VSCode and currently only described as being reproducible in Visual Studio 2019.

**Comment by vexingly** [comment]
Visual Studio 2022 is on the AVD approved software list, has anyone asked for it to be installed? I can't imagine there is any reason to restrict the community edition...

**Comment by rochellegarner** [comment]
That's good to know, @vexingly. If we are allowed to request Visual Studio 2022, we will definitely ask for updated versions. Our problem is getting Visual Studio installed with the proper C++ extensions. It often takes a couple of "tries" before the install is done correctly, because it requires intervention from IT (i.e., the analyst can't simply install from the Software Centre)
