### ISSUE TITLE
StatCan model development investigation and learning

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#16]
Let's learn about the model development requirements and frameworks that are used at StatCan so we can better support them once they start working on their new platform.

**Comment by KrisWilliamson** [comment]
Finished reading Modgen book.  **Microsimulation and Population Dynamics. Belanger and Sabourin**  Borrowed from Statcan Library

**Comment by KrisWilliamson** [comment]
Here is a link to the GCDocs folder (internal to StatCan) where we’ve saved the series of Modgen presentations that we use for training. https://gcdocs.gc.ca/statcan/llisapi.dll/app/nodes/18106785

**Comment by KrisWilliamson** [comment]
Closed as an ongoing task.  If any documentation is found in the future regarding training for Modgen, update this ticket.
