### ISSUE TITLE
Docs: OpenM++ user facing documentation

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#20]
## Requirements

Add user facing docs to the AAW [repo](https://github.com/StatCan/aaw)/[user](https://statcan.github.io/aaw/en/) docs. 

This documentation should include:
- [ ] nuances which relate to the storage of models on blob-csi buckets 
- [ ] using the OpenM++ web app to deploy models
- [ ] monitoring the status of the MPIjobs (currently done via `kubectl logs ...`)
- [ ] French Translation Issue
- [ ] Redo OpenM++ getting started documentation.

**Comment by KrisWilliamson** [comment]
I created a new branch for the User documentation and uploaded a markdown version.
(https://stats-cloud.slack.com/archives/C05PC8VK0Q6/p1700501588254509)
https://github.com/StatCan/openmpp/blob/20-docs-openm++-user-facing-documentation/documentation/GettingStarted/GettingStarted.md

**Comment by KrisWilliamson** [comment]
Doc and images moved to:
https://github.com/StatCan/aaw/blob/openMpp%2320_Docs/docs/en/8-MicroSim/GettingStarted.md
at the request of @Souheil-Yazji
