### ISSUE TITLE
Create Convenient way to shutdown/restart OMS process

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#27]
The OMS process may be preventing file deletion in the `bin` directory. It also needs to be restarted in order to pickup the changes in the bin directory (i.e new files). My current workaround is `kill <pid>`

**Comment by PedramHaeri** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by vexingly** [comment]
There is a script I was going to add here https://github.com/StatCan/aaw-kubeflow-containers/pull/526/files#diff-0ddd5aba5667aa5db4abd9ce438a5ec8701e5d221292c22fa146acc13e9c2b35 to restart the web-ui safely.

**Comment by Souheil-Yazji** [comment]
I'm going to mark this as done since I merged your PR in @vexingly
