### ISSUE TITLE
Contribution to OpenMPP Upstream #0

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#34]
< to be filled out > 

## Scope of Work
Create a markdown document that lists the Parameters used in the project.

### Objective
* Learn the internals of OpenM compiler (omc)
* Produce documentation for model users.
* Create a markdown document that lists the Parameters used in the project.
* Convert the created markdown document into html format.
* Create versions for each supported language (EN and FR)

### Components Modified
* A file called model_doc_intro.cpp was created containing a new function do_model_doc that creates the markdown document.
* this function was called from omc.cpp

#### Repo/PR

https://github.com/openmpp/main

### Other Notes
The https://github.com/progsource/maddy project was used to convert markdown to html.
This project was used at Steve's suggestion as there is markdown embedded in some user content.

**Comment by KrisWilliamson** [comment]
Initial push of branch https://github.com/openmpp/main/tree/model_doc_intro made Dec 13th.

**Comment by KrisWilliamson** [comment]
As of 20 December 2023, The following have been done:
* Markdown file created.
* EN and FR version of Markdown created and put into their own dirs.
  *  /openm/doc/EN/TOC_EN.md
* Markdown converted to html using maddy.
* Table of Contents table created with links to expanded Parameter definition.
* Various markdown formatting fixes made to allow better conversion to html.

**Comment by KrisWilliamson** [comment]
Prettied up some output.
converted Dimension/shape output to a table.
converted Group info to a table
Pushed changes to GitHub.
