### ISSUE TITLE
Implement MPI job spec programmatically

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#41]
Dependant on: #45

**Comment by jacek-dudek** [comment]
Here is a subset of the types that will be participating in creating and submitting an mpi job specification in code, and their package import paths:

k8s.io/client-go/rest
    Config
k8s.io/client-go/kubernetes
    ClientSet
core "k8s.io/api/core/v1
    PodTemplateSpec
    PodSpec
    Container
    ResourceRequirements
    ResourceList
k8s.io/apimachinery/pkg/apis/meta/v1
    ListOptions
    GetOptions
github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1
    MPIJobSpec
    ReplicaSpec
    RunPolicy

**Comment by jacek-dudek** [comment]
I have the in-code mpijob specification figured out. I will try to figure out the appropriate method calls to the mpijob api endpoint for submitting and listing mpijob specs by the end of today to close out the issue.

**Comment by jacek-dudek** [comment]
I'm still trying to grok how to interact with the clientset object in-code.
