### ISSUE TITLE
Search for  a resource specific package for MPI jobs

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#45]

**Comment by jacek-dudek** [comment]
I found the golang package that contains the type declarations that I need to interact with mpi jobs from inside a go program. Some of the relevant types are: MPIJob, MPIJobList, MPIJobSpec, JobStatus, CleanPodPolicy, ReplicaType, ReplicaSpec, ReplicaStatus.

This is the import statement to use to import the package into your go source code:
import github.com/kubeflow/training-operator/pkg/apis/kubeflow.org/v1

This is a link to a searchable index of golang packages that was useful in my search: https://pkg.go.dev
It lets you search published packages by package name or by symbol name. 
It also lets the browse the package contents and in-code documentation.
