### ISSUE TITLE
Feat: database connection improvements

### ISSUE THREAD

**Issue by KrisWilliamson** [StatCan/openmpp#53]
---
name: Feature request
about: Improve OpenM database connectivity
title: 'Feat: Improve OpenM database connectivity
labels: kind/feature
assignees: ''

---

#### Is your feature request related to a problem? Please link issue ticket
Multiple JIRAs.
https://jirab.statcan.ca/projects/OPENM/issues/OPENM-29

There is an known issue with database corruption while running OpenM.

#### Describe the solution you'd like
Improve how Database connectivity is handled in OpenM.  Suggestions include
- Add an argument to the command line that gives a path to the SQLite DB. If not given, default to current behavior of looking for the db in the same directory as the executable. The OpenM.DbPath argument exists but there are integration issues.
  - It appears there is no functionality to pass values to the application from the command line using this argument flag. 
- Investigate using another database other than SQLite and determine how difficult it would be to implement.
  - In a meeting with OpenM on 2024-02-06, it was admitted that although support for databases other than SQLite exists, the functionality has not been tested for years.

#### Additional context
Start of a wish list of features that we can either ask OpenM++ to implement, or we can implement and push back to the OpenM++ project.
RElated to: https://github.com/StatCan/openmpp/issues/39

**Comment by Souheil-Yazji** [comment]
stale
