### ISSUE TITLE
Feat: Modify dispatcher error msg

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#58]
#### Is your feature request related to a problem? Please link issue ticket
Relating to https://github.com/StatCan/openmpp/issues/51

https://github.com/StatCan/openmpp/blob/main/mpi-job-files/dispatchMPIJob.sh#L11

#### Describe the solution you'd like

Instead of "did you compile it?", we can provide the targeted path in the error msg, this will help with debugging.

**Comment by KrisWilliamson** [comment]
Superseded by https://github.com/StatCan/openmpp/issues/47.

**Comment by KrisWilliamson** [comment]
Re-opened at Souheil's request
