### ISSUE TITLE
Cluster Run Options selection causes an error

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#6]
Under the Cluster Run Options menu, setting the MPI Number of Processes to anything other than zero will cause an error.

See https://github.com/StatCan/aaw/issues/1839#issuecomment-1726278613 for more details.

**Comment by Souheil-Yazji** [comment]
I think this might be only an issue when the `_mpi` variation of the model is not present in the model dir. 
If that's the case, and the error is graceful (i.e doesn't kill oms) then we're ok to close this in my opinion.
