### ISSUE TITLE
Bug: ini file binding

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/openmpp#60]
#### Describe the bug

The ini file currently is not referenced correctly in the MPI exec command. We need to reference the correct ini file as it contains the list of output tables to retain among other configs. It is also an option in the UI to support.

#### Environment info

Namespace: all

Notebook/server: all

#### Steps to reproduce

1. Open OMS
2. select a model and config output tables
3. submit job and look at manifest
4. check mpijob logs and see that it ignores the ini file 

#### Expected behaviour

The ini files directory to be correct. The name of the ini file is: <timestamp>.<modelname>.ini

#### Screenshots

![image](https://github.com/StatCan/openmpp/assets/35379392/ce6628bb-921c-4760-8ef5-07ba5a7862df)

**Comment by KrisWilliamson** [comment]
InputArguments from OMC when ini file used.
```./bin/parseCommand.py -modelName IDMM -exeStem IDMM -dir /home/jovyan/buckets/aaw-unclassified/microsim/models/bin -binDir . -dbPath /home/jovyan/buckets/aaw-unclassified/microsim/models/bin/IDMM.sqlite -mpiNp 1 -hostFile -OpenM.RunStamp 2024_02_05_20_08_19_932 -OpenM.LogToConsole true -OpenM.LogToFile false -OpenM.SetName Default -OpenM.LogRank true -OpenM.MessageLanguage en-US -OpenM.RunName IDMM_Default_2024_02_05_15_07_59_717 -OpenM.NotOnRoot -ini ../../logs/2024_02_05_20_08_19_932.IDMM.ini```

file `2024_02_05_20_08_19_932.IDMM.ini` exists in the logs dir, but appears to be malformed.

**Comment by KrisWilliamson** [comment]
From the MPIJob-.yaml file
``` 
#<mpirunOption>
            - /bin/bash
            - -c
            - "ulimit -s 63356 && /home/jovyan/buckets/aaw-unclassified/microsim/models/bin/IDMM_mpi -OpenM.RunStamp 2024_02_05_20_19_19_140 -OpenM.LogToConsole true -OpenM.LogToFile false -OpenM.RunName IDMM_Default_2024_02_05_15_18_49_403 -OpenM.SetName Default -OpenM.IniFile IDMM.ini -OpenM.IniAnyKey true -OpenM.LogRank true -OpenM.MessageLanguage en-US -OpenM.NotOnRoot -ini"
 ```
The -ini argument is right at the end, but is missing its value, the path to the ini file.

**Comment by KrisWilliamson** [comment]
The value is ending up in the unrecognizedCmdLineOptions file.
```
-exeStem
IDMM
-dir
/home/jovyan/buckets/aaw-unclassified/microsim/models/bin
-binDir
.
-dbPath
/home/jovyan/buckets/aaw-unclassified/microsim/models/bin/IDMM.sqlite
-hostFile
../../logs/2024_02_05_20_19_19_140.IDMM.ini
```

**Comment by KrisWilliamson** [comment]
Superseded by https://github.com/StatCan/openmpp/issues/47

**Comment by KrisWilliamson** [comment]
Reopened at Souheil's request.
