### ISSUE TITLE
Deploy OpenM++ image to Dev cluster

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#7]
Directly related to the work done here https://github.com/StatCan/aaw-kubeflow-containers/pull/518
Let's work on a JupyterLab image that includes the OPenM++ OMS UI.

**Comment by vexingly** [comment]
@chuckbelisle can you clarify is this ticket for the Openm++ OMS web-ui integration into the Jupyterlab/other aaw images ?

**Comment by chuckbelisle** [comment]
@vexingly yes, I updated the description of the issue and I can confirm that it is directly related to the OMS web-ui integration with the JupyterLab images.

**Comment by vexingly** [comment]
Thanks for the clarification @chuckbelisle, with the merge of https://github.com/StatCan/aaw-kubeflow-containers/pull/518 the OMS web-ui is now available in our dev and prod jupyterlab images! 

Although I did start a new PR (https://github.com/StatCan/aaw-kubeflow-containers/pull/526) to resolve some code review comments and a few usability issues that I've noticed, more testing feedback is welcomed!
